version: '3.4'

services:
  gbmdb:
    container_name: gbmdb
    environment:
        SA_PASSWORD: "Admin1234$"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1433:1433"

  gbm.challenge.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "ConnectionStrings:GbmConnectionString=Server=gbmdb;Database=GbmChallenge;User Id=sa;Password=Admin1234$"
    depends_on:
        - gbmdb
    ports:
      - "8001:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro